- name: Setup Remi PHP 7 Repo
  yum:
    name: http://rpms.famillecollet.com/enterprise/remi-release-7.rpm
    state: present

- name: Install MySQL, PHP, Git
  yum:
    name:
      - mariadb-server
      - php-fpm
      - php-mysql
      - php-pdo
      - python-pip
      - git
      - mysql-devel
      - python-devel
      - python-setuptools
      - gcc
    state: present
    enablerepo: remi-php72
  notify: restart nginx
  
- name: Start Services
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - mariadb
    - php-fpm
  notify: restart nginx

- file:
    path: /var/lib/php/session/
    owner: nginx
    group: nginx
    mode: 0777
    state: directory

- name: Install asciidoc packages (RHEL)
  yum:
    name:
      - asciidoc
      - rubygem-asciidoctor
    state: present
    enablerepo: rhui-REGION-rhel-server-optional
#  when: ansible_distribution == 'RedHat'


- name: Create users directory on server
  file:
    path: /usr/share/nginx/html/register/
    state: directory

- name: Copy users file to server
  copy:
    src: templates/index.html
    dest: /usr/share/nginx/html/register/index.php
  tags: update

- name: Copy insert file to server
  copy:
    src: templates/insert.php
    dest: /usr/share/nginx/html/register/insert.php
  tags: update


#- name: Install asciidoctor-pdf Gem
#  gem:
#    name: asciidoctor-pdf
#    version: 1.5.0.alpha.6
#    state: present
#
#- name: Build PDF Docs
#  command: asciidoctor -b pdf -d book -r asciidoctor-pdf -o aww.pdf index.adoc
#  args:
#    chdir: /usr/share/nginx/html
#  when: copycontent.changed

- name: Install PyMySQL
  pip:
    name: PyMySQL

- name: Install MySQL-python
  pip:
    name: MySQL-python
    
- name: Create a new database with name 'workshop'
  mysql_db:
    name: ansibleworkshop
    state: present
  tags: sql

- name: reload nginx
  service:
    name: nginx
    state: reloaded
  tags: update

- name: restart nginx
  service:
    name: nginx
    state: restarted
  tags: update
